db-name: feed_test.db
last-episode-only: True
feed: [URL/to/MP3/feed]
force-upload: True
video-height: 1080
video-width: 1920
video-background-color: #164AB8
video-fps: 1
video-codec:libx264
video-bitrate: 800k
font-size-max: 90
font-size-min: 18
font-color: #FFFFFF
font-color-subtitle: #ffffff
title-pos-top: -480
subtitle-pos-top: 350
background-image: backgroundColor.png
temp-path: tmp/
font: font.eot
output: output/
audio-codec: libmp3lame
preview: false
yt_client_secrets_file: assets/client_secret.json

